## ***Matrices in Python***

A matrix is a two-dimensional collection of numbers arranged in rows and columns. In Python, we can represent matrices using nested lists or, more commonly, using libraries like NumPy which provide powerful tools for matrix operations.

In [2]:
import numpy as np

In [3]:
# Example matrices
# A 2x2 matrix (2 rows, 2 columns)
A = np.array([[1, 2],
              [3, 4]])

# A 2x3 matrix (2 rows, 3 columns)
B = np.array([[1, 2, 3],
              [4, 5, 6]])

# A 3x2 matrix (3 rows, 2 columns)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Matrix A (2x2):")
print(A)
print(f"\nShape: {A.shape}  (rows={A.shape[0]}, columns={A.shape[1]})")
print()

print("Matrix B (2x3):")
print(B)
print(f"\nShape: {B.shape}  (rows={B.shape[0]}, columns={B.shape[1]})")
print()

print("Matrix C (3x2):")
print(C)
print(f"\nShape: {C.shape}  (rows={C.shape[0]}, columns={C.shape[1]})")

Matrix A (2x2):
[[1 2]
 [3 4]]

Shape: (2, 2)  (rows=2, columns=2)

Matrix B (2x3):
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)  (rows=2, columns=3)

Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Shape: (3, 2)  (rows=3, columns=2)


### Accessing Matrix Elements

In [5]:
#Example: Accessing matrix elements
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Matrix A:")
print(A)
print(f"\nShape: {A.shape}")
print()

# Accessing elements
print("Accessing elements:")
print(f"A[0, 0] = {A[0, 0]}  (first row, first column)")
print(f"A[0, 1] = {A[0, 1]}  (first row, second column)")
print(f"A[1, 0] = {A[1, 0]}  (second row, first column)")
print(f"A[1, 1] = {A[1, 1]}  (second row, second column)")
print(f"A[2, 0] = {A[2, 0]}  (third row, first column)")
print()

# Accessing entire rows
print("Accessing rows:")
print(f"A[0, :] = {A[0, :]}  (first row)")
print(f"A[1, :] = {A[1, :]}  (second row)")
print()

# Accessing entire columns
print("Accessing columns:")
print(f"A[:, 0] = {A[:, 0]}  (first column)")
print(f"A[:, 1] = {A[:, 1]}  (second column)")

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Shape: (3, 2)

Accessing elements:
A[0, 0] = 1  (first row, first column)
A[0, 1] = 2  (first row, second column)
A[1, 0] = 3  (second row, first column)
A[1, 1] = 4  (second row, second column)
A[2, 0] = 5  (third row, first column)

Accessing rows:
A[0, :] = [1 2]  (first row)
A[1, :] = [3 4]  (second row)

Accessing columns:
A[:, 0] = [1 3 5]  (first column)
A[:, 1] = [2 4 6]  (second column)


### Matrix Addition

In [7]:
#Example: A + B
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix addition: add corresponding elements
result = A + B

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

print("A + B (add corresponding elements):")
print(result)
print()

# Show step by step
print("Step by step:")
print(f"A[0, 0] + B[0, 0] = {A[0, 0]} + {B[0, 0]} = {result[0, 0]}")
print(f"A[0, 1] + B[0, 1] = {A[0, 1]} + {B[0, 1]} = {result[0, 1]}")
print(f"A[1, 0] + B[1, 0] = {A[1, 0]} + {B[1, 0]} = {result[1, 0]}")
print(f"A[1, 1] + B[1, 1] = {A[1, 1]} + {B[1, 1]} = {result[1, 1]}")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A + B (add corresponding elements):
[[ 6  8]
 [10 12]]

Step by step:
A[0, 0] + B[0, 0] = 1 + 5 = 6
A[0, 1] + B[0, 1] = 2 + 6 = 8
A[1, 0] + B[1, 0] = 3 + 7 = 10
A[1, 1] + B[1, 1] = 4 + 8 = 12


### Scalar Multiplication

In [8]:
# Example: 2 * A, 0.5 * A, -1 * A
A = np.array([[1, 2],
              [3, 4]])
A_doubled = 2 * A      # Multiply every element by 2
A_half = 0.5 * A       # Multiply every element by 0.5
A_negated = -1 * A     # Multiply every element by -1

print("Original matrix A:")
print(A)
print()

print("2 * A (double every element):")
print(A_doubled)
print()

print("0.5 * A (half every element):")
print(A_half)
print()

print("-1 * A (negate every element):")
print(A_negated)
print()

# Show step by step for 2 * A
print("Step by step for 2 * A:")
print(f"2 * {A[0, 0]} = {A_doubled[0, 0]}")
print(f"2 * {A[0, 1]} = {A_doubled[0, 1]}")
print(f"2 * {A[1, 0]} = {A_doubled[1, 0]}")
print(f"2 * {A[1, 1]} = {A_doubled[1, 1]}")

Original matrix A:
[[1 2]
 [3 4]]

2 * A (double every element):
[[2 4]
 [6 8]]

0.5 * A (half every element):
[[0.5 1. ]
 [1.5 2. ]]

-1 * A (negate every element):
[[-1 -2]
 [-3 -4]]

Step by step for 2 * A:
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8


### Matrix Operations

In [11]:
# Summary: Different matrix operations
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([2, 3])

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

print("Vector v:")
print(v)
print()

print("=" * 50)
print("OPERATIONS:")
print("=" * 50)
print()

print("1. Addition: A + B")
print(A + B)
print()

print("2. Scalar multiplication: 3 * A")
print(3 * A)
print()

print("3. Matrix-vector multiplication: A @ v")
print(A @ v)
print()

print("4. Matrix-matrix multiplication: A @ B")
print(A @ B)
print()

print("5. Transpose: A.T")
print(A.T)
print()

print("6. Element-wise multiplication (NOT matrix multiplication!): A * B")
print(A * B)
print("(This multiplies each corresponding element separately)")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Vector v:
[2 3]

OPERATIONS:

1. Addition: A + B
[[ 6  8]
 [10 12]]

2. Scalar multiplication: 3 * A
[[ 3  6]
 [ 9 12]]

3. Matrix-vector multiplication: A @ v
[ 8 18]

4. Matrix-matrix multiplication: A @ B
[[19 22]
 [43 50]]

5. Transpose: A.T
[[1 3]
 [2 4]]

6. Element-wise multiplication (NOT matrix multiplication!): A * B
[[ 5 12]
 [21 32]]
(This multiplies each corresponding element separately)
