### ***Tensors in PyTorch***
A Torch Tensor (specifically torch.Tensor in PyTorch) is the fundamental data structure used to build neural networks, acting as a multi-dimensional array of a single data type

In [1]:
import torch
import numpy as np

In [ ]:
import torch

# 1. Creating a Torch Tensor
# Create a 3x3 matrix (2D Tensor) from a Python list
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
my_tensor = torch.tensor(data)

print(f"Original Tensor:\n{my_tensor}")

# ---
# 2. Checking Key Attributes
# ---

print("\n--- Attributes ---")
# Shape: The size of the tensor in each dimension
print(f"Shape: {my_tensor.shape}")

# Size: Total number of elements in the tensor
print(f"Size: {my_tensor.numel()}")

# Dimensions: Number of dimensions (axes) of the tensor
print(f"Number of dimensions: {my_tensor.dim()}")

# Data Type: The type of data stored (e.g., 32-bit integer)
print(f"Data Type: {my_tensor.dtype}")

# Device: Where the tensor is currently stored (e.g., CPU)
print(f"Device: {my_tensor.device}")

# Requires Grad: Is PyTorch tracking operations on this tensor for backpropagation?
print(f"Requires Grad: {my_tensor.requires_grad}")

# ---
# 3. Moving the Tensor to the GPU (if CUDA is available)
# ---

if torch.cuda.is_available():
    # Define the target device
    device = torch.device("cuda")
    
    # Move the tensor to the GPU for faster computation
    gpu_tensor = my_tensor.to(device)
    
    print("\n--- GPU Tensor ---")
    print(f"GPU Tensor:\n{gpu_tensor}")
    print(f"New Device: {gpu_tensor.device}")
else:
    print("\nCUDA (GPU) not available, tensor remains on CPU.")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

--- Attributes ---
Shape: torch.Size([3, 3])
Size: 9
Number of dimensions: 2
Data Type: torch.int64
Device: cpu
Requires Grad: False

CUDA (GPU) not available, tensor remains on CPU.


In [3]:
# Create tensor filled with zeros
zeros_1d = torch.zeros(5)
print("1D tensor of zeros:")
print(zeros_1d)
print()

1D tensor of zeros:
tensor([0., 0., 0., 0., 0.])



In [4]:
# Create tensor filled with zeros with specific shape
zeros_2d=torch.zeros((3,4))
print("2D tensor of zeros (3x4):")
print(zeros_2d)

2D tensor of zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# Tensor filled with ones values
ones_2d = torch.ones((3, 4))
print("2D tensor of ones (3 rows, 4 columns):")
print(ones_2d)
print()

2D tensor of ones (3 rows, 4 columns):
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



In [25]:
# Converting Numpy array to tesnor
np_array=np.array([[1,2,3],[4,5,6]])

print("NumPy array:")
print(np_array)
print(type(np_array))
print(np_array.shape)
print('-'*40)
np_tensor=torch.tensor(np_array)
print("Tensor :")
print(np_tensor)
print(type(np_tensor))
print(np_tensor.shape)

## Convert PyTorch tensor to NumPy

tensor_arr=np_tensor.numpy()
print('-'*40)
print("Converted Array:")
print(tensor_arr)
print(type(tensor_arr))
print(tensor_arr.shape)

NumPy array:
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
----------------------------------------
Tensor :
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.Size([2, 3])
----------------------------------------
Converted Array:
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


### Tensor with random values

In [26]:
# Random values between 0 and 1
random_tensor = torch.rand(3, 4)
print("Random tensor (values between 0 and 1):")
print(random_tensor)
print()

Random tensor (values between 0 and 1):
tensor([[0.0221, 0.5090, 0.1778, 0.5145],
        [0.6846, 0.7376, 0.3823, 0.6673],
        [0.1404, 0.0295, 0.7018, 0.2643]])



In [31]:
# Random integers
random_int = torch.randint(0, 10, (3, 4))
print("Random integers (0 to 9):")
print(random_int)
print()


Random integers (0 to 9):
tensor([[8, 9, 6, 7],
        [6, 3, 0, 9],
        [6, 7, 6, 3]])



In [32]:
# Random values from normal distribution (mean=0, std=1)
normal_tensor = torch.randn(3, 4)
print("Random values from normal distribution:")
print(normal_tensor)
print()

Random values from normal distribution:
tensor([[ 0.1501,  0.8908, -1.2203,  0.6021],
        [-0.6134, -0.7315, -0.6222, -0.9130],
        [ 0.6940,  0.9494, -1.3179,  0.8586]])



In [33]:
# Random values with specific range
random_range = torch.rand(3, 4) * 10  # Scale to 0-10
print("Random values scaled to 0-10:")
print(random_range)

Random values scaled to 0-10:
tensor([[5.0737, 9.8499, 7.2489, 7.8868],
        [0.9038, 5.0991, 1.4299, 1.9489],
        [7.6510, 3.4976, 4.8480, 6.9665]])


In [34]:
t_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float32 tensor:")
print(t_float32)
print(f"dtype: {t_float32.dtype}")
print()

Float32 tensor:
tensor([1., 2., 3.])
dtype: torch.float32



In [35]:
# Convert between types
t_convert = torch.tensor([1, 2, 3], dtype=torch.int64)
t_float_converted = t_convert.float()
print("Converted to float:")
print(t_float_converted)
print(f"dtype: {t_float_converted.dtype}")
print()

Converted to float:
tensor([1., 2., 3.])
dtype: torch.float32



### ***Key Tensor Properties***

**Creating Tensors**
- `torch.tensor([...])` – from a Python list
- `torch.zeros(shape)` – filled with zeros
- `torch.ones(shape)` – filled with ones
- `torch.rand(shape)` – random values (0–1)
- `torch.randn(shape)` – random values from a normal distribution
- `torch.from_numpy(array)` – create a tensor from a NumPy array

**Important Properties**
- `tensor.shape` – dimensions of the tensor
- `tensor.dtype` – data type (float32, int64, etc.)
- `tensor.dim()` – number of dimensions

**Reminder**
- Tensors are the building blocks of PyTorch!
