## Matrix Multiplication in PyTorch
- Matrix multiplication is essential for neural networks! PyTorch provides efficient operations for multiplying matrices and tensors.

In [1]:
import torch

### ***Standard Matrix Multiplication***


In [4]:
A=torch.tensor([[1,2],
                [2,3]],dtype=torch.float32)
B=torch.tensor([[4,5],
                [6,7]],dtype=torch.float32)

mul=A@B

print(mul)
print(f"Shape: {mul.shape}")

tensor([[16., 19.],
        [26., 31.]])
Shape: torch.Size([2, 2])


In [5]:
#Matrix-Vector Multiplication
A=torch.tensor([[1,2,3],
                [4,5,6]],dtype=torch.float32)
B=torch.tensor([7,8,9],dtype=torch.float32)

mul=A@B

print(mul)
print(f"Shape: {mul.shape}")

tensor([ 50., 122.])
Shape: torch.Size([2])


In [9]:
# How it works
print("How it works:")
print(f"Result[0] = A[0, 0]*B[0] + A[0, 1]*B[1] = {A[0, 0]}*{B[0]} + {A[0, 1]}*{B[1]}+{A[0, 2]}*{B[2]} = {mul[0]}")
print(f"Result[1] = A[1, 0]*B[0] + A[1, 1]*B[1] = {A[1, 0]}*{B[0]} + {A[1, 1]}*{B[1]}+{A[1, 2]}*{B[2]} = {mul[1]}")

How it works:
Result[0] = A[0, 0]*B[0] + A[0, 1]*B[1] = 1.0*7.0 + 2.0*8.0+3.0*9.0 = 50.0
Result[1] = A[1, 0]*B[0] + A[1, 1]*B[1] = 4.0*7.0 + 5.0*8.0+6.0*9.0 = 122.0


In [ ]:
# Batch Matrix Multiplication
# Create batch of matrices: (batch_size, rows, cols)
batch_A = torch.randn(3, 2, 4)  # 3 matrices, each 2×4
batch_B = torch.randn(3, 4, 3)  # 3 matrices, each 4×3

batch_result = torch.bmm(batch_A, batch_B)
print("Batch matrix multiplication result:")
print(batch_result)
print(f"Shape: {batch_result.shape}")
print("(3 matrices, each 2×3)")
print()

Batch matrix multiplication result:
tensor([[[-0.2796,  1.1144, -3.5100],
         [ 3.6206, -1.4536, -2.7449]],

        [[ 1.9632, -0.2000,  1.7870],
         [-1.0798, -1.8258, -6.3744]],

        [[-2.0814,  4.5125,  0.9834],
         [-1.1376, -2.2991,  0.3868]]])
Shape: torch.Size([3, 2, 3])
(3 matrices, each 2×3)



In [12]:
# Element-wise multiplication
element_wise = A * B
print("A * B (element-wise multiplication):")
print(element_wise)
print()
print(f"Shape: {element_wise.shape}")

A * B (element-wise multiplication):
tensor([[ 7., 16., 27.],
        [28., 40., 54.]])

Shape: torch.Size([2, 3])


In [13]:
# Matrix multiplication (for comparison)
matrix_mult = A @ B
print("A @ B (matrix multiplication):")
print(matrix_mult)
print()


A @ B (matrix multiplication):
tensor([ 50., 122.])

